cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'node'
brew 'nvm'
brew 'uv'
brew 'wget'
brew 'zsh-syntax-highlighting'

cask 'alfred'
cask 'antigravity'
cask 'arq'
cask 'bartender'
cask 'claude'
cask 'claude-code'
cask 'cursor'
cask 'gemini-cli'
cask 'google-chrome'
cask 'notion'
cask 'visual-studio-code'
cask 'warp'
