cask_args appdir: '/Applications'

brew 'gemini-cli'
brew 'git'
brew 'node'
brew 'nvm'
brew 'ollama'
# brew 'starship'
brew 'uv'
brew 'wget'
brew 'zsh-syntax-highlighting'

cask 'alfred'
cask 'antigravity'
# cask 'arq'
cask 'claude'
cask 'claude-code'
cask 'cursor'
cask 'ghostty'
cask 'google-chrome'
cask 'notion'
cask 'visual-studio-code'
